// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qekvorbfjgzdfpanwnfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFla3ZvcmJmamd6ZGZwYW53bmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NzA4MTUsImV4cCI6MjA0OTU0NjgxNX0.paLxUOfLcoLIPuyREIAKcjLpho8G_D9YBlrMqS8ngn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);